Swap stage added to workflow.

diff --git a/.github/workflows/blue-green-environment-workflow.yml b/.github/workflows/blue-green-environment-workflow.yml
--- a/.github/workflows/blue-green-environment-workflow.yml
+++ b/.github/workflows/blue-green-environment-workflow.yml
@@ -57,8 +57,11 @@ jobs:
     steps:
       - name: Output environment values
         run: |
-          echo "Environment: ${{ needs.get-active-environment.outputs.env }}"
-          echo "Project Directory: ${{ needs.get-active-environment.outputs.project_dir }}"
+          # echo "Environment: ${{ needs.get-active-environment.outputs.env }}"
+          # echo "Project Directory: ${{ needs.get-active-environment.outputs.project_dir }}"
+
+          echo "Environment: ${{ env.env }}"
+          echo "Project Directory: ${{ env.project_dir }}"
 
       - name: Check out code
         uses: actions/checkout@v3
@@ -71,3 +74,29 @@ jobs:
 
       - name: Install Composer dependencies
         run: composer install --no-dev --optimize-autoloader
+
+
+  swap:
+      runs-on: ubuntu-latest
+      needs: deploy
+      if: success()
+      steps:
+        - name: Set up SSH
+          uses: webfactory/ssh-agent@v0.5.3
+          with:
+            ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}
+
+        - name: Swap Environments
+          run: |
+            ssh -p 65002 -o StrictHostKeyChecking=no u605848448@217.21.77.232 << 'EOF'
+            CURRENT_TARGET=$(readlink /home/u605848448/domains/michael-gibbs-testing.site/public_html/current)
+
+            if [[ "$CURRENT_TARGET" == "/home/u605848448/domains/michael-gibbs-testing.site/blue/public/" ]]; then
+              ln -sfn /home/u605848448/domains/michael-gibbs-testing.site/green/public/ /home/u605848448/domains/michael-gibbs-testing.site/public_html/current
+            elif [[ "$CURRENT_TARGET" == "/home/u605848448/domains/michael-gibbs-testing.site/green/public/" ]]; then
+              ln -sfn /home/u605848448/domains/michael-gibbs-testing.site/blue/public/ /home/u605848448/domains/michael-gibbs-testing.site/public_html/current
+            else
+              echo "ERROR: Unknown current target: $CURRENT_TARGET"
+              exit 1
+            fi
+            EOF
